version: "3"

services:
  minecraft:
    ports:
      - "25565:25565"
    volumes:
      - /minecraft-server:/data
    environment:
      OVERRIDE_SERVER_PROPERTIES: "true"
      MODE: "survival"
      DIFFICULTY: "hard"
      ALLOW_NETHER: "true"
      GENERATE_STRUCTURES: "true"
      SPAWN_ANIMALS: "true"
      SPAWN_MONSTERS: "true"
      SPAWN_NPCS: "true"
      LEVEL_TYPE: DEFAULT
      VIEW_DISTANCE: 10
      MAX_PLAYERS: 10
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "true"
      SNOOPER_ENABLED: "false"
      MAX_TICK_TIME: 60000
      MAX_MEMORY: 3750M
      INIT_MEMORY: 1G
      MAX_BUILD_HEIGHT: 256
      HARDCORE: "false"
      ICON: "https://i.imgur.com/n08GKJR.jpg"
      EULA: "true"
      TYPE: PAPER
      VERSION: 1.15.2
    command: --noconsole
    image: itzg/minecraft-server
    container_name: minecraft
    restart: always
